### ISSUE TITLE
input config via command args

### ISSUE THREAD

**Issue by calvintam236** [semtexzv/Prospector#1]
I mine using docker, so having a physical config file would be a lot of headache (if you know how to build a docker image).. especially current alpha can't designated config file location -- I would prefer config via command args. I would also install it at `/usr/local/bin`, so config file path has to be editable.

I don't mind keeping the physical config file for people who prefer that way.

**Comment by semtexzv** [comment]
Having only config file without configuration provided through flags was explicit design decision, so adding one know is not an option.

Miner supports setting config file location by passing `--config <path>`  option. If you are using same configuration for all your miners, you could use NFS attached directory.

**Comment by MircoBlitz** [comment]
Using a config file with Docker should not in any way be a headache. I only write config files in my docker projects. ENV Override is a bad style. (on the security part)

**Comment by calvintam236** [comment]
Using one config file isn't a problem, but there is a case that you would like to run individual miner for each GPU on docker (better crash restart/coin switching and GPU monitoring), and you will need to deploy them with different worker name per miner/GPU (create docker volume -> edit each config for different worker name -> run the container), this is a lot of work and time. For now, I will just use `xmrig` and `ethminer` because they provide such command options and yours don't.
