### ISSUE TITLE
Prospector v007 crashes after about 1h

### ISSUE THREAD

**Issue by MircoBlitz** [semtexzv/Prospector#10]
Error:

20:06:30 - INFO   Signatum: Average 14.34M, 13.63M, 13.17M Hash/s (30s, 5m, 30m)
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Abgebrochen (Speicherabzug geschrieben)

**Comment by semtexzv** [comment]
std::bad_alloc is C++ exception.

Miner is not written in C++, so it is unlikely this is in the core code of the miner. Could be a driver issue.

Are you on Linux/Windows? What driver are you using ?

**Comment by MircoBlitz** [comment]
I am running amdgpu-pro-17.10-429170 on ubuntu linux 16.04.3 LTS

Tell me what log I should send and I will do

v0.0.6 is running stable

**Comment by semtexzv** [comment]
You opened another issue with miner Crashing on startup. Since you resolved that issue with reinstall,
please report whether this issue still occurs.

**Comment by MircoBlitz** [comment]
fixed in 008 (or with openCL install)
