### ISSUE TITLE
Startup error under Linux in v008

### ISSUE THREAD

**Issue by MircoBlitz** [semtexzv/Prospector#11]
HI, I get this startup error under Linux.

ubuntu 16.04
v0.0.8
info.db deleted

2x rx460 2GB

> 15:48:01 - INFO   prospector 0.0.8-ALPHA starting
> 15:48:01 - INFO   Configuration successfuly loaded from config.json
> 15:48:02 - INFO   OpenCL initialized
> 15:48:02 - INFO   Not launching CPU miner
> 15:48:02 - INFO    Miner starting on gpu (0:0) - Baffin
> 15:48:02 - INFO    Miner starting on gpu (0:1) - Baffin
> 15:48:02 - INFO   Device (0:2) disabled
> 15:48:02 - ERROR  Worker (0:0) error: Error(Ocl(
> 
> ################################ OPENCL ERROR ############################### 
> 
> Error executing function: clCreateCommandQueue  
> 
> Status error code: CL_OUT_OF_HOST_MEMORY (-6)  
> 
> Please visit the following url for more information: 
> 
> https://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clCreateCommandQueue.html#errors  
> 
> ############################################################################# 
> ), State { next_error: None, backtrace: None }) restarting
> 15:48:02 - ERROR  Worker (0:1) error: Error(Ocl(
> 
> ################################ OPENCL ERROR ###############################
> 
> Error executing function: clCreateCommandQueue  
> 
> Status error code: CL_OUT_OF_HOST_MEMORY (-6)  
> 
> Please visit the following url for more information: 
> 
> https://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clCreateCommandQueue.html#errors  
> 
> ############################################################################# 
> ), State { next_error: None, backtrace: None }) restarting

After that, you miner is <defunct> and unable to be killed. Only solution is to restart the system.

All my Issues for you are FYI ;-)

**Comment by MircoBlitz** [comment]
If you trust me not ripping your code, I'd try a local compile. (Your choice, I'm a dev myself and not interested in programing a miner myself)

**Comment by semtexzv** [comment]
I have experienced this myself on Arch linux, and don't have a fix yet. Is the older version working ?

**Comment by MircoBlitz** [comment]
reinstalling opencl helped.

**Comment by semtexzv** [comment]
What driver version are you using ? AMDGPU or AMDGPU-PRO, what opencl driver ? i would like to create a wiki page with these things.

**Comment by MircoBlitz** [comment]
Ubuntu 16.04 LTS
2x Geforce RX460 modded ROM

clinfo-amdgpu-pro             16.40-348864   
libopencl1-amdgpu-pro:amd64   16.40-348864   
libopencl1-amdgpu-pro:i386    16.40-348864   
ocl-icd-libopencl1:amd64      2.2.8-1        
ocl-icd-opencl-dev:amd64      2.2.8-1        
opencl-amdgpu-pro-icd:amd64   16.40-348864   
opencl-amdgpu-pro-icd:i386    16.40-348864   
opencl-headers                2.0~svn32091-2

7,46Mh/s / RX460 with 5% OC
