### ISSUE TITLE
OPENCL ERROR

### ISSUE THREAD

**Issue by kschroed** [semtexzv/Prospector#13]
Proespector runs well on 0.0.6-ALPHA release on my system at around 18Mhs per RX 480 8GB card.  Upgrading to 0.0.7-ALPHA prospector is unstable and freeze after 15 minutes or so.  Upgraded to 0.0.8-ALPHA and proespector will not start with: 
Error executing from function: clCreateCommandQueue
Status error code: OPEN CL ERROR CL_OUT_FHOST_MEMORY (-6)

Running opencl-amdgpu-pro-icd 17.10 on ubuntu 14.04 ethos build w/ 4GB host memory and 7xRX480 8GB cards.

**Comment by MircoBlitz** [comment]
Use 0.0.8-ALPHA and upgrade  to opencl-amdgpu-pro-icd 17.30 or downgrade to opencl-amdgpu-pro-icd 16.40

**Comment by kschroed** [comment]
I've tried running both 17.30 and 16.40 drivers now on clean install of Ubunto 16.04 with 0.0.8-ALPHA and 0.0.9-ALPHA and getting the same error.  0.0.6-ALPHA still works on new system build.

**Comment by MircoBlitz** [comment]
I second that with V0.1.0 under Ubuntu 16.04
