### ISSUE TITLE
Memory saturation

### ISSUE THREAD

**Issue by gdcfxvnjvbncvb** [semtexzv/Prospector#14]
Hello,

I have problems with the Skunk prospector algorithm (with v0.0.10-ALPHA; untested on the older versions).
It uses up all my Memory (RAM) and Swap (Page file) and then crashes ...
I have 8Go of memory and a swap of 24Go.
http://i.imgur.com/U0pVdv6.png

My cards : 
Nvidia GTX 1080Ti
Nvidia GTX 1060 6Go
AMD Radeon RX480 4Go

My config.json file for the Nvidia GTX 1080Ti :
```
{
  "pools": {
    "sigt": {
      "url": "skunk.eu.nicehash.com:3362",
      "username": "address.worker1",
      "password": "x"
    }
  },
  "gpus": {
    "(0:0)": {
      "enabled": true,
      "label": "GeForce GTX 1080 Ti"
    }
  },
  "cpu": {
    "enabled": false,
    "label": "CPU"
  },
  "gpu-coin": "sigt"
}
```

Best regards,
gdcfxvnjvbncvb

**Comment by semtexzv** [comment]
This issue crops up for some users, only thing that seems to fix the issue is updating the drivers.

**Comment by Phoenix983** [comment]
I'M HEREBY TO CONFIRM THAT IS TRUE, HAPPENED TO ME RIGHT NOW, I HAVE 8 GB RAM AND 32 GB PAGEFILE, SAME ERROR.

**Comment by Phoenix983** [comment]
IF IT HELPS, MY OS FOR THAT ISSUE WIN 8.1 - AMD FURY X 4 GB

**Comment by Phoenix983** [comment]
SATURATION IS NOT HAPPENING WITH CRIMSON 15.12 DRIVERS, I HAS BEEN MINING ALL THE NIGHT STABLE WITH THAT DRIVER WITHOUT ANY MEMORY SATURATION ISSUE, SAPPHIRE R9 FURY 4GB WIN 8.1, BUT IF I USE 16.3.2 DRIVERS I GET THE MEMORY SATURATION ERROR. CATCH IT @semtexzv 

THE UNIQUE BAD NEWS OF ALL THIS, IS ABOUT THE HASHRATE, DROPS TOO MUCH WITH 15.12 DRIVER, (4.00 MH/S) COMPARED TO 16.3.2 (14.95 MH/S)

**Comment by Phoenix983** [comment]
TESTING WITH CRIMSON 16.12.2:
Sapphire R9 280x 384 bits (overclock 1100 mhz - stock memory 1500 mhz @ 3.15 MH/s) (Working & tested driver crimson 16.12.2) Windows 10 (Total Speed 9.45 MH/s)
GPU LOAD: 85% EACH CARD, IT CAN BE OPTIMIZED.

Sapphire R9 Fury 4096 bits (overclock 1100 mhz - stock memory 500 mhz @ 20.90 MH/s) (Working & tested driver crimson 16.12.2) Windows 8.1 (Total Speed 41.80 MH/s)

NO MEMORY SATURATION ISSUE WITH THESE DRIVERS, @gdcfxvnjvbncvb TEST YOUR RX 480 WITH THAT VERSION.

**Comment by gdcfxvnjvbncvb** [comment]
@semtexzv @Phoenix983 Sorry for the late reply.
I was using driver version 16.11.5 and was having memory issues with it.
I installed driver version 17.8.2 and can run prospector without any issues.

If you have any memory saturating problems, update your drivers.
