### ISSUE TITLE
All shares rejected at suprnova pool

### ISSUE THREAD

**Issue by Phoenix983** [semtexzv/Prospector#15]
Hello Dev! thank you very much for this miner, I want to let you know that I have a rig with 3 sapphire dual-x r9 280x 3 GB memory and I don't know if it is a miner, suprnova pool or new algoritm issued level but all my shares are rejected :< suprnova worker USERNAME and PASSWORD are correct and I had the same issue with sgminer too, miner reports 2.63 mh/s speed by each card and a GPU use of 89%, I'm using crimson 16.3.2 and they works like a charm with nicehash algoritm and claymore miner, may I know what happend with my tahiti's GPU'S and the new Skunkhash? I have another rig with 2 sapphire r9 fury cards 4GB and it works perfect at a beautiful speed of 14.85 mh/s each 100% GPU.

I hope you can tell me what to do to mine signatum with my tahitis.

Regards.

**Comment by semtexzv** [comment]
Well, older cards don't work, I do not have any of them for testing, so I can't fix it currently, simple as that.

**Comment by Phoenix983** [comment]
Ok semtexzv, I need to report to you that now is fully working, I just installed crimson 15.12 and that solved the issue, that is the magic driver version for those cards, but with prospector, my 3 tahiti's are not working at they 100% percent GPU load, just 89-90% with a 2.65 mh/s per GPU, if I use sgminer, it deliver 4.52 mh/s, for a total of 12 mh/s approximately 99% GPU load, please, improve performance for R9 280x cards too, they are still used nowadays.

**Comment by Phoenix983** [comment]
I still getting the same issue with sgminer 5.3.3 updated for skunkhash algoritm, miner works like normal but never found & send a share, but with your prospector miner, I have confirmed that works with crimson 15.12, you just need to optimize it to get the full profitability with that tahiti gpu r9 280x.
