### ISSUE TITLE
Centos 7.3 `GLIBC_2.18' not found

### ISSUE THREAD

**Issue by teshy** [semtexzv/Prospector#17]
Error launching prospector-0.0.12-ALPHA-linux64
./prospector: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./prospector)

I confirmed it is installed:
Package glibc-2.17-196.el7.i686 already installed and latest version

any help please?

**Comment by semtexzv** [comment]
Well, you have installed 2.17, but you need 2.18

I will try to compile the binary with older version of libc in the future, but I have to create an architecture for that ( Few VMs , build scripts etc ... )
