### ISSUE TITLE
Other Coin with ethash Algo

### ISSUE THREAD

**Issue by e-bon** [semtexzv/Prospector#19]
Hi,

Is there any possibility to use Prospector to mine another EThash coin? e.g Ubiq, Soilcoin, etc.
Have beent try, but after 30 minutes got some error.

`09:28:02 - ERROR   Nonce 350000049b4ff9 resulted in  e82954e07465a076
09:28:03 - INFO   Ethereum: Share submitted
09:28:05 - INFO   Ethereum: Shares    11 accepted / 22 total`

**Comment by semtexzv** [comment]
Nvidia or AMD?, what version ?

**Comment by e-bon** [comment]
AMD Version, I use it to mine Musicoin on miningpoolhub.

**Comment by e-bon** [comment]
Windows 10 64
