### ISSUE TITLE
[win10+rx 480] crash while creating DAG file

### ISSUE THREAD

**Issue by jokerle** [semtexzv/Prospector#2]
After about 88% Win10 display first freezes, and then goes black. Need to hit reset button. Afaik PC still runs (music still plays), just display driver(?) died.
[info.zip](https://github.com/semtexzv/Prospector/files/1160305/info.zip)

not sure how i can provide anything more.

**Comment by semtexzv** [comment]
Thank you, but the info.db is not used for much currently, it will be in the future.
I know where the issue occurs and tried to fix it with the newest release.

Can you try running version 0.0.2 ? Should fix this issue

**Comment by jokerle** [comment]
I just tried. Same issue, doesn't seem to behave any differently.

**Comment by semtexzv** [comment]
Can you post the output of the miner at the time of the crash ? Also, are you running the miner on system with any other GPU intensive applications ( Other miners, Games ...) ?

**Comment by jokerle** [comment]
ok, i piped the output into a file:
```
00:13:36 - INFO   prospector 0.0.2-ALPHA starting
00:13:36 - INFO   Configuration successfuly loaded from config.json
00:13:37 - INFO   OpenCL initialized
00:13:37 - INFO   Not launching CPU miner
00:13:37 - INFO    Miner starting on gpu (0:0) - Ellesmere
00:13:37 - INFO   Device (0:1) disabled
00:13:37 - INFO   Ethereum: Subscribed, waiting for jobs
00:13:37 - INFO   Ethereum: Authorized  by the pool
00:13:37 - INFO   Ethereum: Miner received subscription response
00:13:37 - INFO   Ethereum: Miner received new job
00:13:37 - INFO   Epoch changed to : 135
00:13:37 - INFO   CREATING DAG on (0:0)
00:13:38 - INFO   DAG upload on GPU (0:0) - 0.00 %
00:13:40 - INFO   DAG upload on GPU (0:0) - 11.11 %
00:13:41 - INFO   DAG upload on GPU (0:0) - 22.22 %
00:13:43 - INFO   DAG upload on GPU (0:0) - 33.33 %
00:13:44 - INFO   DAG upload on GPU (0:0) - 44.44 %
00:13:46 - INFO   DAG upload on GPU (0:0) - 55.56 %
00:13:47 - INFO   DAG upload on GPU (0:0) - 66.67 %
00:13:49 - INFO   DAG upload on GPU (0:0) - 77.78 %
00:13:49 - INFO   Ethereum: Miner received new job
00:13:50 - INFO   DAG upload on GPU (0:0) - 88.89 %
00:13:50 - INFO   DAG upload on GPU (0:0) - 100.00% (Complete)
```

Well, this looks good! But my screen still first freezes and then goes black (no display output).
edit: I tested it with a freshly booted win10 as well.

**Comment by jokerle** [comment]
With V.0.0.5 the display still goes black but recovers quickly.
The miner is not running correctly afterwards and gives 0.00 Hash/s:
(even after 5min)

```
18:21:09 - INFO   DAG upload on GPU (0:0) - 88.89 %
18:21:09 - INFO   DAG upload on GPU (0:0) - 100.00% (Complete)
18:21:18 - INFO   Ethereum: Shares   0 accepted / 0 total
18:21:18 - INFO   Ethereum: Devices (0:0) - 0.00Hash/s 
18:21:18 - INFO   Ethereum: Average 0.00, 0.00, 0.00 Hash/s (30s, 5m, 30m)
18:21:34 - INFO   Ethereum: Miner received new job
18:21:40 - INFO   Ethereum: Shares   0 accepted / 0 total
18:21:40 - INFO   Ethereum: Devices (0:0) - 0.00Hash/s 
18:21:40 - INFO   Ethereum: Average 0.00, 0.00, 0.00 Hash/s (30s, 5m, 30m)
18:21:51 - INFO   Ethereum: Miner received new job
18:21:57 - INFO   Ethereum: Miner received new job
18:22:03 - INFO   Ethereum: Shares   0 accepted / 0 total
18:22:03 - INFO   Ethereum: Devices (0:0) - 0.00Hash/s 
18:22:03 - INFO   Ethereum: Average 0.00, 0.00, 0.00 Hash/s (30s, 5m, 30m)
```

edit: PC needs a restart afterwards as the GPU is no longer correctly detected, e.g. from various miners.

**Comment by semtexzv** [comment]
I found the issue, and am working on resolving it right now.

**Comment by semtexzv** [comment]
Version 0.0.8 should fix the problem.

**Comment by jokerle** [comment]
working now! Nicely done.

closing the issue.

**Comment by semtexzv** [comment]
Finally !! 👍
