### ISSUE TITLE
error while loading shared libraries: libprocps.so.6

### ISSUE THREAD

**Issue by calvintam236** [semtexzv/Prospector#20]
```console
$ ./prospector
./prospector: error while loading shared libraries: libprocps.so.6: cannot open
shared object file: No such file or directory
```

on version v0.0.13

Any idea how to run it? No idea what package is this library come from.

**Comment by semtexzv** [comment]
No idea mate, search your distribution's package manager

**Comment by Phil795** [comment]
@semtexzv Same issue here. 

- Ubuntu 16.04
- CUDA 9.1
- NVIDIA Cards

Any ideas?
There is no libprocps.so.6 lib for ubuntu...
