### ISSUE TITLE
UNable to mine on AMD GPU with prospector as Config file fails

### ISSUE THREAD

**Issue by MrT63** [semtexzv/Prospector#21]
running Prospector gen-config gives this config file
[general]
gpu-coin = "sigt"
cpu-coin = "xmr"
default-username = "18FcsT6g5FtrFwXiWsxCZ1M3fbKfdG531W"
default-password = "x"
[pools.eth]
url = "stratum+tcp://daggerhashimoto.eu.nicehash.com:3353/"
[pools.sia]
url = "stratum+tcp://sia.eu.nicehash.com:3360/"
[pools.sigt]
url = "stratum+tcp://skunk.eu.nicehash.com:3362/"
[pools.xmr]
url = "stratum+tcp://cryptonight.eu.nicehash.com:3355/"
[pools.zec]
url = "stratum+tcp://equihash.eu.nicehash.com:3357/"
[gpus.0-0]
enabled = true
label = "GeForce GTX 970"
[cpu]
enabled = false
label = "CPU"

Upon changing it to substitute my Aerium wallet address as the User and the Password as c-AERM it becomes

[general]
gpu-coin = "sigt"
cpu-coin = "xmr"
default-username = "AZf7JzaPwCkjLnbTtmSDDtTcLW9UnCLskW"
default-password = "c=AERM"
[pools.eth]
url = "stratum+tcp://daggerhashimoto.eu.nicehash.com:3353/"

[pools.sia]
url = "stratum+tcp://sia.eu.nicehash.com:3360/"

[pools.sigt]
url = "stratum+tcp://skunk.eu.nicehash.com:3362/"

[pools.xmr]
url = "stratum+tcp://cryptonight.eu.nicehash.com:3355/"

[pools.zec]
url = "stratum+tcp://equihash.eu.nicehash.com:3357/"
[gpus.0-0]
enabled = true
label = "GeForce GTX 970"

[cpu]
enabled = false
label = "CPU"

on running prospector  i just get solid disconnected.  All firewalls disabled

![aerium](https://user-images.githubusercontent.com/31526720/32975703-2084277a-cc45-11e7-8ee9-caef3b4f3fad.png)

Any suggestions on correct format for the config.toml file? for amd

**Comment by MrT63** [comment]
i dont want to mine signatum actually i want o mine Aerium... soooo how to do i put in user name and pass for aerium - i did try adding u= and p= on the skunk line

[general]
gpu-coin = "sigt"
cpu-coin = "xmr"
default-username = "AZf7JzaPwCkjLnbTtmSDDtTcLW9UnCLskW"
default-password = "c=AERM"
[pools.eth]

url = "stratum+tcp://sia.eu.nicehash.com:3360/"

[pools.sigt]

url = "stratum+tcp://skunk.eu.nicehash.com:3362/"

[pools.xmr]
 -u "AZf7JzaPwCkjLnbTtmSDDtTcLW9UnCLskW"
 -p c=AERM
url = "stratum+tcp://cryptonight.eu.nicehash.com:3355/"

[pools.zec]

url = "stratum+tcp://equihash.eu.nicehash.com:3357/
"
[gpus.0-0]
enabled = true
label = "GeForce GTX 970"

[cpu]
enabled = false
label = "CPU"

then I get a "could not parse configuration file " error

**Comment by semtexzv** [comment]
If Aerium uses same algo as signatum, enter pool information into signatum part, and pretend you are mining signatum. Config file does not accept `-p` parameters. only `username="text"` and `password="text"` are accepted. The format is TOML (https://npf.io/2014/08/intro-to-toml/)
