### ISSUE TITLE
Lose connection and crash

### ISSUE THREAD

**Issue by thormenos** [semtexzv/Prospector#22]
After an hour or so, it crash because it can't connect. I have to restart it and everything work fine after for another hour.. With xfx 570 using skunk algo

**Comment by semtexzv** [comment]
This is probably due to Nicehash problems right now. If nicehash does not come back up soon, I will create a new  version that uses a different server for devfee.

**Comment by ElJabato** [comment]
Same problem.

ERROR  Could not connect to stratum+tcp://skunk.eu.nicehash:3362/ after 10 attempts, exiting

**Comment by bobekook** [comment]
Same problem please help me fix.

ERROR  Could not connect to stratum+tcp://skunk.eu.nicehash:3362/ after 10 attempts, exiting

**Comment by semtexzv** [comment]
This was due to nicehash problems, They seem to be fine now
