### ISSUE TITLE
Prospector mines on my CPU as a GPU

### ISSUE THREAD

**Issue by platonicjesus** [semtexzv/Prospector#25]
Prospector will decide to mine on my CPU as a GPU even though CPU mining is disabled. It looks like this:
19:41:14 - INFO   Not launching CPU miner
19:41:14 - INFO   Miner starting on gpu 0-0 - gfx901
19:41:14 - INFO   Miner starting on gpu 0-1 - AMD Ryzen 7 1800X Eight-Core Processor

**Comment by UselessGuru** [comment]
> https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1215

But your APU has GPU installed. You may have to specify the CPU's you really want to use in the toml config file
`[gpus.1-0]`
`enabled = true` -> `enabled = false`
where you will need to figure your the proper values for `[gpus.1-0]`

**Comment by platonicjesus** [comment]
My CPU is not an APU and has no GPU cores.

**Comment by UselessGuru** [comment]
To turn off CPU mining: If the toml file has a section saying
```
[cpu]
enabled = true
```

then change that to 
```
[cpu]
enabled = false
```

Based on the info in your first post prospector is mining it should not be mining on gpu 0-1. So
change
```
[gpus.0-1]
enabled = true
```
to
```
[gpus.0-1]
enabled = false
```

**Comment by platonicjesus** [comment]
I understand the workaround but no other miner sees my CPU as a GPU.

**Comment by semtexzv** [comment]
Well, this is caused by current device detection system, You just have to manually disable specific devices. 

The default generated configuration should not try to use CPUs as GPUs
