### ISSUE TITLE
Prospector pays no attention to my configuration settings in regards to an Nvidia card despite loading the config.toml file.

### ISSUE THREAD

**Issue by ghost** [semtexzv/Prospector#26]
I tell it to disable mining in OpenCL for an Nvidia card sitting at device 0-0. What does it do? It goes ahead and initializes the card and tries to compile an OpenCL 1.2 kernel for it (which this device doesn't support) and it ends in an error. Now, this is interesting, the CPU stays disabled but the first device, which is an Nvidia card will not disable no matter what I have in the configuration file. I'm filing this one as a bug.

I can't for the life of me get it to disable or not use that card, no matter what I do.

The config.toml file looks like this.

[general]
gpu-coin = "sigt"
default-username = "19ZXJshBr7Ydp5Ko5827b15e7UVUEZK7uJ.worker1"
default-password = "x"
[pools.sigt]
url = "stratum+tcp://skunk.usa.nicehash.com:3362"
[gpus.0-0]
enabled = false
label = "GeForce GTX 560 Ti"
[gpus.1-0]
enabled = true
label = "Capeverde"
[gpus.2-0]
enabled = true
label = "Capeverde"
[cpu]
enabled = false

The version I am using is the following; prospector 0.0.10-ALPHA

Now, this happens on Linux and in Windows, so it's not an operating system, Linux distribution, driver or OpenCL implementation problem.

**Comment by UselessGuru** [comment]
Development seem to have stopped. :-(

**Comment by ghost** [comment]
That's a bummer!

**Comment by semtexzv** [comment]
Please include output of `prospector list-devices -v`

**Comment by ghost** [comment]
I no longer use this software. Thanks, though.
