### ISSUE TITLE
cannot generate config file

### ISSUE THREAD

**Issue by MircoBlitz** [semtexzv/Prospector#5]
Hi, i get the following error on ubuntu 16.04.3 LTS.

○ → ./prospector gen-config
11:41:11 - INFO   prospector 0.0.5-ALPHA starting
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:335
note: Run with `RUST_BACKTRACE=1` for a backtrace.

Thank you for your work

**Comment by semtexzv** [comment]
Please run `RUST_BACKTRACE=full ./prospector gen-config` and `RUST_BACKTRACE=full ./prospector list-devices -v` and post results here.

This is probably error during GPU load, or some small mistake, I need output of these commands to know which.

**Comment by MircoBlitz** [comment]
○ → RUST_BACKTRACE=full ./prospector gen-config
15:43:04 - INFO   prospector 0.0.5-ALPHA starting
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:335
stack backtrace:
   0:     0x7f15a937df93 - <unknown>
   1:     0x7f15a937ab48 - <unknown>
   2:     0x7f15a9379b5b - <unknown>
   3:     0x7f15a93794ff - <unknown>
   4:     0x7f15a9379369 - <unknown>
   5:     0x7f15a938ed46 - <unknown>
   6:     0x7f15a938f5ed - <unknown>
   7:     0x7f15a91e4526 - <unknown>
   8:     0x7f15a91ebb79 - <unknown>
   9:     0x7f15a805582f - __libc_start_main
  10:     0x7f15a90aa4c9 - <unknown>
  11:                0x0 - <unknown>

○ → RUST_BACKTRACE=full ./prospector list-devices -v
15:43:44 - INFO   prospector 0.0.5-ALPHA starting
15:43:45 - INFO   Platform 0 - AMD Accelerated Parallel Processing
15:43:45 - INFO   Device (0:0) - Baffin
15:43:45 - INFO                   Type : DEVICE_TYPE_GPU
15:43:45 - INFO                 Vendor : Advanced Micro Devices, Inc.
15:43:45 - INFO         OpenCL Version : OpenCL 1.2 AMD-APP (2117.10)
15:43:45 - INFO         Driver Version : 2117.10 (VM)
15:43:45 - INFO            Addres bits : 64
15:43:45 - INFO          Little endian : true
15:43:45 - INFO        Max clock freq. : 555
15:43:45 - INFO          Compute units : 14
15:43:45 - INFO    Max local work size : 256
15:43:45 - INFO    Max work dimensions : [256, 256, 256]
15:43:45 - INFO    Max allocation size : 1243985510
15:43:45 - INFO   
15:43:45 - INFO   Device (0:1) - Baffin
15:43:45 - INFO                   Type : DEVICE_TYPE_GPU
15:43:45 - INFO                 Vendor : Advanced Micro Devices, Inc.
15:43:45 - INFO         OpenCL Version : OpenCL 1.2 AMD-APP (2117.10)
15:43:45 - INFO         Driver Version : 2117.10 (VM)
15:43:45 - INFO            Addres bits : 64
15:43:45 - INFO          Little endian : true
15:43:45 - INFO        Max clock freq. : 555
15:43:45 - INFO          Compute units : 14
15:43:45 - INFO    Max local work size : 256
15:43:45 - INFO    Max work dimensions : [256, 256, 256]
15:43:45 - INFO    Max allocation size : 1243985510
15:43:45 - INFO   
15:43:45 - INFO   Device (0:2) - AMD A6-3650 APU with Radeon(tm) HD Graphics
15:43:45 - INFO                   Type : DEVICE_TYPE_CPU
15:43:45 - INFO                 Vendor : AuthenticAMD
15:43:45 - INFO         OpenCL Version : OpenCL 1.2 AMD-APP (2117.10)
15:43:45 - INFO         Driver Version : 2117.10 (sse2)
15:43:45 - INFO            Addres bits : 64
15:43:45 - INFO          Little endian : true
15:43:45 - INFO        Max clock freq. : 2600
15:43:45 - INFO          Compute units : 4
15:43:45 - INFO    Max local work size : 1024
15:43:45 - INFO    Max work dimensions : [1024, 1024, 1024]
15:43:45 - INFO    Max allocation size : 4201790464
15:43:45 - INFO

**Comment by semtexzv** [comment]
Ok, it's not device discovery, it's my own stupidity, that caused this bug :). 

I will upload version 0.0.6 momentarily, please see if it fixes this issue.

Thank you

**Comment by MircoBlitz** [comment]
Thank you very very much. I now got it running.

Here the numbers of my small test rig (2x RX460 unpatched)

Signatum only
sgminer = 11,45mh/s
Prospector = 13,46Mh/s

So thats 2mh/s up on RX460 Please continue optimizing skunk. 
If you need help (testing for example) just drop me a line (@lindworm on twitter).
thx
