### ISSUE TITLE
[Minor] Counting seems to be off

### ISSUE THREAD

**Issue by MircoBlitz** [semtexzv/Prospector#7]
Hi semtexzv,

I recognized the counting of shares is off. 

Example 1: 
22:57:36 - INFO   Signatum: Shares   1231 accepted / **1234** total
22:57:36 - INFO   Signatum: Devices (0:0) - 6.97MHash/s (0:1) - 6.64MHash/s
22:57:36 - INFO   Signatum: Average 12.84M, 13.37M, 13.42M Hash/s (30s, 5m, 30m)
**22:57:37 - INFO   Signatum: Share submitted
22:57:42 - INFO   Signatum: Share submitted
22:57:45 - INFO   Signatum: Share submitted
22:57:55 - INFO   Signatum: Share submitted**
22:57:58 - INFO   Signatum: Shares   1234 accepted / **1237** total
22:57:58 - INFO   Signatum: Devices (0:0) - 6.77MHash/s (0:1) - 6.77MHash/s 
22:57:58 - INFO   Signatum: Average 13.57M, 13.37M, 13.42M Hash/s (30s, 5m, 30m)
22:58:00 - INFO   Signatum: Share submitted
22:58:06 - INFO   Signatum: Miner received n

Example 2:
INFO   Signatum: Shares   1237 accepted / **1240** total
22:58:20 - INFO   Signatum: Devices (0:0) - 6.92MHash/s (0:1) - 6.69MHash/s 
22:58:20 - INFO   Signatum: Average 13.29M, 13.36M, 13.42M Hash/s (30s, 5m, 30m)
**22:58:28 - INFO   Signatum: Share submitted
22:58:33 - INFO   Signatum: Share submitted
22:58:35 - INFO   Signatum: Share submitted
22:58:36 - INFO   Signatum: Share submitted**
22:58:42 - INFO   Signatum: Shares   1238 accepted / **1241** total
22:58:42 - INFO   Signatum: Devices (0:0) - 6.77MHash/s (0:1) - 6.64MHash/s 
22:58:42 - INFO   Signatum: Average 13.49M, 13.36M, 13.42M Hash/s (30s, 5m, 30m)

I wonder if this is due to a multithread (you log the sending but not the recieving (accept/decline) while another thread is logging out the Info it has in cache (which then could not be accurate)

But please don't waste time on it :-)

**Comment by semtexzv** [comment]
Yes, share count takes some time to update, not a big deal really.
