### ISSUE TITLE
Please add XMR mining support on GPU

### ISSUE THREAD

**Issue by hoyanf** [semtexzv/Prospector#8]
Kindly add support for mining monero on GPU as some of us does mine on GPU+CPU for monero.

Thanks

**Comment by semtexzv** [comment]
Well, it's planed, but currently I have my hands full with Signatum.

**Comment by amity203** [comment]
Now Sign was done 10 days back, any progress on adding XMR for GPU as this is the right time

**Comment by aaronsace** [comment]
@semtexzv Just rip the algorithm code from Zawawawa's old GatelessGate miner; they have moved to the closed source NiceHash Excavator miner now so it's abandoned: 
https://github.com/zawawawa/gatelessgate

NiceHash are threatening legal action just for linking to their new Excavator binary file so it's not ideal to be used with https://github.com/aaronsace/MultiPoolMiner. 

You have the beginnings of a top miner here; keep up the great work!

**Comment by sikkapay** [comment]
Any update if you are considering GPU mining for cryptonote algo

**Comment by semtexzv** [comment]
Well, you are in luck, I've just finished basic OpenCL XMR Miner. It will be released soon :)

**Comment by amity203** [comment]
Awesome! waiting to mine with that!

**Comment by tonytnnt** [comment]
Ran into an error trying to mine XMR on OpenCL. Info.db and last log file are attached.
[info.zip](https://github.com/semtexzv/Prospector/files/1616542/info.zip)

**Comment by semtexzv** [comment]
Should be working in v0.1.0
